#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          2

bspc config split_ratio            0.50
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true
bspc config ignore_ewmh_focus      true

bspc rule -a Google-chrome:google-chrome desktop='^1' follow=off
bspc rule -a Code desktop='^2' follow=off
bspc rule -a vlc desktop='^3' follow=off
bspc rule -a discord desktop='^9' follow=off
bspc rule -a Google-chrome:crx_hnpfjngllnobngcgfapefoaidbinmjnm desktop='^10' follow=off
bspc rule -a Google-chrome:crx_kippjfofjhjlffjecoapiogbkgbpmgej desktop='^8' follow=off
